spring:
  profiles:
    group:
      "local": "localDB, devPort"
      "dev": "devDB, devPort"
    active: "local"

---

spring:
  config:
    activate:
      on-profile: "localDB"
  datasource:
    url: jdbc:mysql://localhost:3306/letscareer_c
    username: root
    password: duswn123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: "devDB"
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 9000
