name: cd

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types: [ completed ]
    branches: [ "main", "dev" ]

jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 via SSH
        uses: appleboy/ssh-action@master
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          envs: APPLICATION_PROPERTIES
          script: |
            cd /home/ubuntu/Backend
            
            rm -rf src/main/resources/application.yml
            
            git pull origin main
            
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            echo "$APPLICATION_PROPERTIES" > app_property.txt
            echo "${{ secrets.SERVER_PORT }}" > server_port.txt
            
            ./gradlew clean
            
            ./gradlew build -x test
            
            sudo fuser -k -n tcp "${{ secrets.SERVER_PORT }}" || true
            
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
